/**
 * Integration tests run the real Express app against a real database. They create and mutate data,
 * so they must never point at a shared or production project.
 */
const path = require('path');

if (process.env.FARMRENT_ENV_FILE) {
    require('dotenv').config({ path: path.resolve(process.cwd(), process.env.FARMRENT_ENV_FILE) });
}

const required = ['SUPABASE_URL', 'SUPABASE_SERVICE_KEY', 'DATABASE_URL', 'JWT_SECRET', 'JWT_REFRESH_SECRET'];
const missing = required.filter((key) => !process.env[key]);
if (missing.length) {
    throw new Error(
        `Integration tests need ${missing.join(', ')}. Start the local stack (docker compose up -d db rest gateway redis) ` +
            'and run with FARMRENT_ENV_FILE=.env.localstack (generated by scripts/setup-local-env.js), or export the variables.',
    );
}

const host = new URL(process.env.SUPABASE_URL).hostname;
if (!['localhost', '127.0.0.1', 'gateway'].includes(host) && process.env.ALLOW_NON_LOCAL_TEST_DB !== 'true') {
    throw new Error(`Refusing to run integration tests against ${host}. Use the local Docker stack.`);
}

process.env.NODE_ENV = 'test';
