"""add_indexes_for_performance

Revision ID: a58271c48381
Revises: 8bbb1b346e35
Create Date: 2026-06-14 22:41:41.994314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a58271c48381'
down_revision: Union[str, Sequence[str], None] = '8bbb1b346e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'idx_bookings_overlap',
        'bookings',
        ['equipment_id', 'start_date', 'end_date'],
        unique=False,
        postgresql_where=sa.text("booking_status IN ('requested', 'pending', 'confirmed', 'active')"),
        sqlite_where=sa.text("booking_status IN ('requested', 'pending', 'confirmed', 'active')")
    )
    op.create_index(op.f('ix_equipment_latitude'), 'equipment', ['latitude'], unique=False)
    op.create_index(op.f('ix_equipment_longitude'), 'equipment', ['longitude'], unique=False)
    op.create_index('idx_user_sessions_jti', 'user_sessions', ['token_jti', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_sessions_jti', table_name='user_sessions')
    op.drop_index(op.f('ix_equipment_longitude'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_latitude'), table_name='equipment')
    op.drop_index(
        'idx_bookings_overlap',
        table_name='bookings',
        postgresql_where=sa.text("booking_status IN ('requested', 'pending', 'confirmed', 'active')"),
        sqlite_where=sa.text("booking_status IN ('requested', 'pending', 'confirmed', 'active')")
    )
    # ### end Alembic commands ###
